name: facedetection
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.5
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  cloud_firestore: ^5.5.0


  # Image + Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9


  # Local storage
  sqflite: ^2.3.2
  path_provider: ^2.0.15
  path: ^1.9.0

  # Face Detection + TFLite
  google_ml_kit: ^0.20.0


  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  checks: ^0.3.0
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/face_recognition_model.tflite
    - assets/models/labels.txt
    #- assets/mobile_facenet.tflite
